### ISSUE TITLE
Cannot create basic ubuntu box using hyperv

### ISSUE THREAD

**Issue by OwenGr** [test-kitchen/kitchen-hyperv#33]
I'm having problems getting kitchen create to run with kitchen-hyperv. The VM creates just fine in Hyper-V Manager, and I can ssh to it from the console using the default user/pass, but kitchen-create hangs here:

```
C:\Source\cookbooks\motd_ubuntu>kitchen create -l debug
-----> Starting Kitchen (v1.10.2)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      Berksfile found at C:/Source/cookbooks/motd_ubuntu/Berksfile, loading Berkshelf
D      Berkshelf 4.3.5 library loaded
-----> Creating <default-ericmann-trusty64>...
D      <default-ericmann-trusty64> is synchronizing on Kitchen::Driver::Vagrant#create
D      <default-ericmann-trusty64> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <default-ericmann-trusty64> (C:/Source/cookbooks/motd_ubuntu/.kitchen/kitchen-vagrant/kitchen-motd_ubuntu-default-ericmann-trusty64/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
D        c.vm.box = "ericmann/trusty64"
D        c.vm.hostname = "default-ericmann-trusty64"
D        c.vm.network(:public_network, {:bridge=>"ExternalSwitch"})
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :hyperv do |p|
D          p.memory = 256
D        end
D      end
D      ------------
D      [Vagrant command] BEGIN (vagrant up --no-provision --provider hyperv)
       Bringing machine 'default' up with 'hyperv' provider...
       ==> default: Verifying Hyper-V is enabled...
       ==> default: Configured startup memory is 256
       ==> default: Importing a Hyper-V instance
       Looking for switch with name: ExternalSwitch
       Found switch: ExternalSwitch
           default: Cloning virtual hard drive...
           default: Creating and registering the VM...
           default: Successfully imported a VM with name: Trusty Tahr
       ==> default: Starting the machine...
       ==> default: Waiting for the machine to report its IP address...
           default: Timeout: 120 seconds
           default: IP: 172.27.50.41
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 172.27.50.41:22
           default: SSH username: vagrant
           default: SSH auth method: password
```

I have a very basic .kitchen.yml:

```

---
driver:
  name: vagrant
  provider: hyperv
  vm_switch: 'ExternalSwitch'
  network:
    - ["public_network", {bridge: 'ExternalSwitch'}]

provisioner:
  name: chef_zero

platforms:
  - name: ericmann/trusty64
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[motd_ubuntu::default]
    attributes:
```

Any ideas what I'm doing wrong?
